### ISSUE TITLE
Android app crashes when generating new word list

### ISSUE THREAD

**Issue by henrivain** [henrivain/WordLists#10]
Some command might not work correctly
 ## Log output
```
---------------------------------------------
2023-01-11 17:20:08.440 +02:00 [INF] New serilogger created in 'DefaultLoggingProvider'.
2023-01-11 17:20:08.490 +02:00 [INF] Application 'WordLists' running version '1.3'
2023-01-11 17:20:08.501 +02:00 [INF] Added global exception handler
2023-01-11 18:27:54.532 +02:00 [INF] ---------------------------------------------
2023-01-11 18:27:54.603 +02:00 [INF] New serilogger created in 'DefaultLoggingProvider'.
2023-01-11 18:27:54.654 +02:00 [INF] Application 'WordLists' running version '1.3'
2023-01-11 18:27:54.662 +02:00 [INF] Added global exception handler
2023-01-11 18:27:57.794 +02:00 [INF] Goto 'ListGeneratorPage' from 'HomePage'
2023-01-11 18:28:12.233 +02:00 [ERR] 'System.Object' threw exception 'NotImplementedException': 'value should not be null', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:28:12.248 +02:00 [ERR] '(null)' threw exception 'NotImplementedException': 'value should not be null', caught with 'HandleAndroidException', see trace 
   at WordListsViewModels.ListGeneratorViewModel.<get_Edit>b__33_0(String value)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Object parameter)
   at Microsoft.Maui.Controls.Button
2023-01-11 18:28:12.301 +02:00 [ERR] 'System.Object' threw exception 'NotImplementedException': 'value should not be null', caught with 'UnhandledException', see trace 
   at WordListsViewModels.ListGeneratorViewModel.<get_Edit>b__33_0(String value)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Object parameter)
   at Microsoft.Maui.Controls.Button
2023-01-11 18:28:15.230 +02:00 [INF] ---------------------------------------------
2023-01-11 18:28:15.301 +02:00 [INF] New serilogger created in 'DefaultLoggingProvider'.
2023-01-11 18:28:15.344 +02:00 [INF] Application 'WordLists' running version '1.3'
2023-01-11 18:28:15.353 +02:00 [INF] Added global exception handler
2023-01-11 18:28:18.083 +02:00 [INF] Goto 'ListGeneratorPage' from 'HomePage'
2023-01-11 18:29:19.140 +02:00 [INF] Initialize new WordCollectionService
2023-01-11 18:29:19.142 +02:00 [INF] Database is stored at /data/user/0/henri_vainio.wordlists/files/WordListsData.db
2023-01-11 18:29:19.580 +02:00 [INF] Created tables for WordCollectionOwner and WordPair
2023-01-11 18:29:19.690 +02:00 [INF] Initialize new WordPairService database at /data/user/0/henri_vainio.wordlists/files/WordListsData.db.
2023-01-11 18:29:19.710 +02:00 [INF] Insert all WordPairs of WordCollection
2023-01-11 18:29:22.044 +02:00 [INF] Added new WordCollection with id '82'.
2023-01-11 18:29:28.087 +02:00 [INF] Get all word WordCollections
2023-01-11 18:29:28.094 +02:00 [INF] Initialize new WordCollectionOwnerService
2023-01-11 18:29:28.096 +02:00 [INF] Database at path: /data/user/0/henri_vainio.wordlists/files/WordListsData.db
2023-01-11 18:29:28.216 +02:00 [INF] Table created in WordCollectionOwnerService
2023-01-11 18:29:28.218 +02:00 [INF] Get all WordCollectionOwners
2023-01-11 18:29:28.275 +02:00 [INF] Get WordPairs by owner id 77.
2023-01-11 18:29:28.365 +02:00 [INF] Get WordPairs by owner id 78.
2023-01-11 18:29:28.399 +02:00 [INF] Get WordPairs by owner id 79.
2023-01-11 18:29:28.429 +02:00 [INF] Get WordPairs by owner id 80.
2023-01-11 18:29:28.463 +02:00 [INF] Get WordPairs by owner id 81.
2023-01-11 18:29:28.466 +02:00 [INF] Get WordPairs by owner id 82.
2023-01-11 18:29:31.936 +02:00 [INF] Get WordCollection with id '82'
2023-01-11 18:29:31.942 +02:00 [INF] Get WordCollectionOwners by id: 82
2023-01-11 18:29:31.970 +02:00 [INF] Get WordPairs by owner id 82.
2023-01-11 18:29:32.207 +02:00 [INF] Start editing WordCollection with name SAA08 Kleidung, Körper, Krankenheiten
2023-01-11 18:29:44.477 +02:00 [INF] Get all WordCollectionOwners
2023-01-11 18:29:47.080 +02:00 [INF] Get all WordCollectionOwners
2023-01-11 18:29:48.663 +02:00 [INF] Get WordCollection with id '82'
2023-01-11 18:29:48.664 +02:00 [INF] Get WordCollectionOwners by id: 82
2023-01-11 18:29:48.684 +02:00 [INF] Get WordPairs by owner id 82.
2023-01-11 18:30:34.858 +02:00 [INF] Get all word WordCollections
2023-01-11 18:30:34.859 +02:00 [INF] Get all WordCollectionOwners
2023-01-11 18:30:35.097 +02:00 [INF] Get WordPairs by owner id 77.
2023-01-11 18:30:35.113 +02:00 [INF] Get WordPairs by owner id 78.
2023-01-11 18:30:35.137 +02:00 [INF] Get WordPairs by owner id 79.
2023-01-11 18:30:35.179 +02:00 [INF] Get WordPairs by owner id 80.
2023-01-11 18:30:35.213 +02:00 [INF] Get WordPairs by owner id 81.
2023-01-11 18:30:35.245 +02:00 [INF] Get WordPairs by owner id 82.
2023-01-11 18:31:25.011 +02:00 [ERR] 'System.Object' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:31:25.025 +02:00 [ERR] '(null)' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'HandleAndroidException', see trace 
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[AndroidX.RecyclerView.Widget.RecyclerView, Xamarin.AndroidX.RecyclerView, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
2023-01-11 18:31:25.041 +02:00 [ERR] 'System.Object' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:31:25.049 +02:00 [ERR] 'System.Object' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:32:06.986 +02:00 [ERR] 'System.Object' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:32:06.987 +02:00 [ERR] '(null)' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'HandleAndroidException', see trace 
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[AndroidX.RecyclerView.Widget.RecyclerView, Xamarin.AndroidX.RecyclerView, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
2023-01-11 18:32:06.990 +02:00 [ERR] 'System.Object' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:32:06.991 +02:00 [ERR] 'System.Object' threw exception 'InvalidOperationException': 'VirtualView cannot be null here', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:32:11.635 +02:00 [ERR] 'System.Object' threw exception 'ArgumentOutOfRangeException': 'ArgumentOutOfRange_ListInsert Arg_ParamName_Name, index', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:32:11.676 +02:00 [ERR] 'System.Object' threw exception 'ArgumentOutOfRangeException': 'ArgumentOutOfRange_ListInsert Arg_ParamName_Name, index', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:32:11.680 +02:00 [ERR] '(null)' threw exception 'ArgumentOutOfRangeException': 'ArgumentOutOfRange_ListInsert Arg_ParamName_Name, index', caught with 'HandleAndroidException', see trace 
   at System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Insert(Int32 , Object )
   at Microsoft.Maui.Controls.MarshalingObservableCollection.Add(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Con
2023-01-11 18:32:11.713 +02:00 [ERR] 'System.Object' threw exception 'ArgumentOutOfRangeException': 'ArgumentOutOfRange_ListInsert Arg_ParamName_Name, index', caught with 'UnhandledException', see trace 
   at System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Insert(Int32 , Object )
   at Microsoft.Maui.Controls.MarshalingObservableCollection.Add(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Con
2023-01-11 18:32:13.773 +02:00 [INF] ---------------------------------------------
2023-01-11 18:32:13.846 +02:00 [INF] New serilogger created in 'DefaultLoggingProvider'.
2023-01-11 18:32:13.889 +02:00 [INF] Application 'WordLists' running version '1.3'
2023-01-11 18:32:13.897 +02:00 [INF] Added global exception handler
2023-01-11 18:32:17.152 +02:00 [INF] Goto 'ListGeneratorPage' from 'HomePage'
2023-01-11 18:32:57.961 +02:00 [INF] Initialize new WordCollectionService
2023-01-11 18:32:57.964 +02:00 [INF] Database is stored at /data/user/0/henri_vainio.wordlists/files/WordListsData.db
2023-01-11 18:32:58.295 +02:00 [INF] Created tables for WordCollectionOwner and WordPair
2023-01-11 18:32:58.384 +02:00 [INF] Initialize new WordPairService database at /data/user/0/henri_vainio.wordlists/files/WordListsData.db.
2023-01-11 18:32:58.411 +02:00 [INF] Insert all WordPairs of WordCollection
2023-01-11 18:32:59.618 +02:00 [INF] Added new WordCollection with id '83'.
2023-01-11 18:34:37.656 +02:00 [INF] Insert all WordPairs of WordCollection
2023-01-11 18:34:39.977 +02:00 [INF] Added new WordCollection with id '84'.
2023-01-11 18:34:51.238 +02:00 [INF] Initialize new WordCollectionOwnerService
2023-01-11 18:34:51.239 +02:00 [INF] Database at path: /data/user/0/henri_vainio.wordlists/files/WordListsData.db
2023-01-11 18:34:51.632 +02:00 [INF] Table created in WordCollectionOwnerService
2023-01-11 18:34:55.872 +02:00 [INF] Get all word WordCollections
2023-01-11 18:34:55.876 +02:00 [INF] Get all WordCollectionOwners
2023-01-11 18:34:55.980 +02:00 [INF] Get WordPairs by owner id 77.
2023-01-11 18:34:56.032 +02:00 [INF] Get WordPairs by owner id 78.
2023-01-11 18:34:56.062 +02:00 [INF] Get WordPairs by owner id 79.
2023-01-11 18:34:56.095 +02:00 [INF] Get WordPairs by owner id 80.
2023-01-11 18:34:56.129 +02:00 [INF] Get WordPairs by owner id 81.
2023-01-11 18:34:56.162 +02:00 [INF] Get WordPairs by owner id 82.
2023-01-11 18:34:56.200 +02:00 [INF] Get WordPairs by owner id 83.
2023-01-11 18:34:56.231 +02:00 [INF] Get WordPairs by owner id 84.
2023-01-11 18:35:00.689 +02:00 [INF] Get WordCollection with id '83'
2023-01-11 18:35:00.695 +02:00 [INF] Get WordCollectionOwners by id: 83
2023-01-11 18:35:00.722 +02:00 [INF] Get WordPairs by owner id 83.
2023-01-11 18:35:00.806 +02:00 [INF] Start editing WordCollection with name SAA08 Körper
2023-01-11 18:35:06.260 +02:00 [ERR] 'System.Object' threw exception 'NotImplementedException': 'value should not be null', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:35:06.281 +02:00 [ERR] '(null)' threw exception 'NotImplementedException': 'value should not be null', caught with 'HandleAndroidException', see trace 
   at WordListsViewModels.ListGeneratorViewModel.<get_Edit>b__33_0(String value)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Object parameter)
   at Microsoft.Maui.Controls.Button
2023-01-11 18:35:06.330 +02:00 [ERR] 'System.Object' threw exception 'NotImplementedException': 'value should not be null', caught with 'UnhandledException', see trace 
   at WordListsViewModels.ListGeneratorViewModel.<get_Edit>b__33_0(String value)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Object parameter)
   at Microsoft.Maui.Controls.Button
2023-01-11 18:35:08.307 +02:00 [INF] ---------------------------------------------
2023-01-11 18:35:08.374 +02:00 [INF] New serilogger created in 'DefaultLoggingProvider'.
2023-01-11 18:35:08.417 +02:00 [INF] Application 'WordLists' running version '1.3'
2023-01-11 18:35:08.424 +02:00 [INF] Added global exception handler
2023-01-11 18:35:11.588 +02:00 [INF] Initialize new WordCollectionOwnerService
2023-01-11 18:35:11.594 +02:00 [INF] Database at path: /data/user/0/henri_vainio.wordlists/files/WordListsData.db
2023-01-11 18:35:12.167 +02:00 [INF] Table created in WordCollectionOwnerService
2023-01-11 18:35:12.258 +02:00 [INF] Initialize new WordPairService database at /data/user/0/henri_vainio.wordlists/files/WordListsData.db.
2023-01-11 18:35:15.532 +02:00 [INF] Initialize new WordCollectionService
2023-01-11 18:35:15.533 +02:00 [INF] Database is stored at /data/user/0/henri_vainio.wordlists/files/WordListsData.db
2023-01-11 18:35:15.743 +02:00 [INF] Created tables for WordCollectionOwner and WordPair
2023-01-11 18:35:15.745 +02:00 [INF] Get all word WordCollections
2023-01-11 18:35:15.748 +02:00 [INF] Get all WordCollectionOwners
2023-01-11 18:35:16.120 +02:00 [INF] Get WordPairs by owner id 77.
2023-01-11 18:35:16.303 +02:00 [INF] Get WordPairs by owner id 78.
2023-01-11 18:35:16.360 +02:00 [INF] Get WordPairs by owner id 79.
2023-01-11 18:35:16.374 +02:00 [INF] Get WordPairs by owner id 80.
2023-01-11 18:35:16.411 +02:00 [INF] Get WordPairs by owner id 81.
2023-01-11 18:35:16.437 +02:00 [INF] Get WordPairs by owner id 82.
2023-01-11 18:35:16.475 +02:00 [INF] Get WordPairs by owner id 83.
2023-01-11 18:35:16.506 +02:00 [INF] Get WordPairs by owner id 84.
2023-01-11 18:35:18.912 +02:00 [INF] Get all word WordCollections
2023-01-11 18:35:18.913 +02:00 [INF] Get all WordCollectionOwners
2023-01-11 18:35:19.020 +02:00 [INF] Get WordPairs by owner id 77.
2023-01-11 18:35:19.042 +02:00 [INF] Get WordPairs by owner id 78.
2023-01-11 18:35:19.062 +02:00 [INF] Get WordPairs by owner id 79.
2023-01-11 18:35:19.095 +02:00 [INF] Get WordPairs by owner id 80.
2023-01-11 18:35:19.129 +02:00 [INF] Get WordPairs by owner id 81.
2023-01-11 18:35:19.162 +02:00 [INF] Get WordPairs by owner id 82.
2023-01-11 18:35:19.195 +02:00 [INF] Get WordPairs by owner id 83.
2023-01-11 18:35:19.234 +02:00 [INF] Get WordPairs by owner id 84.
2023-01-11 18:35:23.786 +02:00 [INF] Get WordCollection with id '83'
2023-01-11 18:35:23.792 +02:00 [INF] Get WordCollectionOwners by id: 83
2023-01-11 18:35:23.819 +02:00 [INF] Get WordPairs by owner id 83.
2023-01-11 18:35:23.999 +02:00 [INF] Start editing WordCollection with name SAA08 Körper
2023-01-11 18:35:28.258 +02:00 [ERR] 'System.Object' threw exception 'NotImplementedException': 'value should not be null', caught with 'FirstChanceException', see trace 
NULL
2023-01-11 18:35:28.280 +02:00 [ERR] '(null)' threw exception 'NotImplementedException': 'value should not be null', caught with 'HandleAndroidException', see trace 
   at WordListsViewModels.ListGeneratorViewModel.<get_Edit>b__33_0(String value)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Object parameter)
   at Microsoft.Maui.Controls.Button
2023-01-11 18:35:28.323 +02:00 [ERR] 'System.Object' threw exception 'NotImplementedException': 'value should not be null', caught with 'UnhandledException', see trace 
   at WordListsViewModels.ListGeneratorViewModel.<get_Edit>b__33_0(String value)
   at CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Object parameter)
   at Microsoft.Maui.Controls.Button
2023-01-11 18:35:33.256 +02:00 [INF] ---------------------------------------------
2023-01-11 18:35:33.312 +02:00 [INF] New serilogger created in 'DefaultLoggingProvider'.
2023-01-11 18:35:33.351 +02:00 [INF] Application 'WordLists' running version '1.3'
2023-01-11 18:35:33.358 +02:00 [INF] Added global exception handler
2023-01-11 18:35:38.268 +02:00 [INF] User requested to copy log files to downloads folder.
2023-01-11 18:35:38.322 +02:00 [INF] Request permission to use StorageRead
2023-01-11 18:35:41.024 +02:00 [INF] Filesystem read access is set to: Granted
2023-01-11 18:35:41.036 +02:00 [INF] Request permission to use StorageWrite
2023-01-11 18:35:41.259 +02:00 [INF] Filesystem wrote access is set to: Granted
2023-01-11 18:35:41.268 +02:00 [INF] Copy file from '/data/user/0/henri_vainio.wordlists/files/Logs/wordlist_runtime.log' to '/storage/emulated/0/Download/WordLists_Logs/'
2023-01-11 18:35:41.271 +02:00 [INF] Create directory to path /storage/emulated/0/Download/WordLists_Logs/
2023-01-11 18:35:41.307 +02:00 [INF] Try delete file at /storage/emulated/0/Download/WordLists_Logs/wordlist_runtime.log.txt
2023-01-11 18:35:41.309 +02:00 [INF] Success, no file found
 

```

**Comment by henrivain** [comment]
Caused by bad binding data type
Fixed with bug #11 fix
